name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test (imports + forward pass shapes)
        run: |
          export PYTHONPATH=.
          python - <<'PY'
          import torch
          from src.models.swin_unet_cpaf import SwinUNetCPAF
          m = SwinUNetCPAF()
          x = torch.randn(1,2,32,32,32)
          p, aux = m(x)
          assert p.shape == (1,1,32,32,32)
          print('OK: swin_unet_cpaf forward', p.shape)

          from src.models.baselines.unet3d import UNet3D
          b = UNet3D(in_channels=2, out_channels=1, base_ch=8, depth=3)
          pb,_ = b(torch.randn(1,2,32,32,32))
          assert pb.shape == (1,1,32,32,32)
          print('OK: unet3d forward', pb.shape)
          PY
